// Deal Workspace — LOCAL i18n dictionary (EN keys are source of truth).
// i18n.ts is shared/owned elsewhere, so this screen's strings live here and
// merge at render via tw(); shared keys still resolve through i18n.t().
import { t as sharedT, type Locale } from "../../i18n";

const en = {
  dealWorkspace: "DEAL WORKSPACE",
  owner: "Owner",
  updated: "Updated",
  offering: "Offering",
  draft: "Draft — not saved",
  savedQuote: "Quote",
  readOnly: "Read-only — your role can view simulations but not save quotes.",
  step1: "Step 1 · Baseline",
  step2: "Step 2 · AI cost of delivery",
  step3: "Step 3 · Pricing model",
  population: "Custom objects in estate",
  scope: "Objects in scope",
  hrsPerUnit: "Trad. effort / object (h)",
  billRate: "Blended bill rate ($/h)",
  costRate: "Loaded delivery cost ($/h)",
  coverage: "AI coverage of objects (c)",
  effort: "Effort reduction (e)",
  qa: "Human QA add-back (q)",
  llm: "LLM ASSUMPTIONS → t",
  tier: "Model tier",
  tokIn: "K tokens in / obj",
  tokOut: "K tokens out / obj",
  overhead: "Agentic retry overhead",
  tokenCostLabel: "AI TOKEN COST / OBJECT (t)",
  platform: "Platform & tooling (P)",
  discount: "Customer discount vs. traditional (d)",
  band: "Published opening band",
  floorHint: "Risk-adjusted max safe discount = %s — beyond this, AI destroys value",
  baseline: "TRADITIONAL BASELINE (NO AI) · U × h × Rb",
  priceUnit: "Price / obj",
  fourChoices: "Same engagement, four pricing choices",
  fourChoicesSub: "All AI scenarios share one cost of delivery — only the pricing logic changes.",
  gainShare: "Gain-share curve — profit vs. customer discount",
  gainShareSub: "Gold dashes = today's traditional profit (%p). The crossover d* = %d is the max discount before AI erodes value.",
  governance: "DEAL GOVERNANCE",
  floor: "Naive floor d*",
  current: "Current d",
  riskMax: "Risk-adj. max",
  gates: "%n GOVERNANCE GATES",
  gatePass: "PASS",
  gateWarn: "WARN",
  gateFail: "FAIL",
  gateSummary: "%p pass · %w warn · %f fail",
  showGates: "Show gate detail",
  hideGates: "Hide gate detail",
  save: "Save",
  export: "Export",
  generate: "Generate proposal",
  copyMd: "Copy as Markdown",
  rev: "Revenue",
  cost: "Cost of delivery",
  gp: "Gross profit",
  margin: "Gross margin",
  revHr: "Rev / delivery hour",
  saves: "Customer saves",
  aiEffort: "Effort with AI",
  duration: "Delivery duration",
  perObj: "per object",
  vsTradHr: "vs $%b traditional",
  belowTrad: "below traditional",
  vsMonths: "vs %m mo traditional",
  vsTraditional: "vs traditional",
  selectedPrefix: "Selected: ",
  unitsInScope: "%n %u in scope",
  monthsShort: "mo",
  hoursShort: "h",
  tokSuffix: "tok",
  // Verdict titles/messages (JA localization of engine governance states)
  within: "WITHIN POLICY",
  review: "DEAL-DESK REVIEW REQUIRED",
  blocked: "BLOCKED — POLICY OR ECONOMIC FLOOR FAILED",
  nobid: "NO-BID / RE-SCOPE",
  msgWithin:
    "Economics and mandatory policy gates pass. Sales may proceed inside the published band.",
  msgReview:
    "The deal remains economically viable but exceeds the normal band or carries unresolved evidence warnings.",
  msgBlocked:
    "At least one mandatory gate or risk-adjusted economic hurdle failed. Do not quote at this price. Route to the deal desk for re-scope, tier restructure or no-bid.",
  msgNobid:
    "The required risk-adjusted price exceeds the willingness-to-pay ceiling. Argue speed, warranty and total cost of rework, restructure scope, or do not bid — do not discount to match.",
  // Contested-bid block
  contestedTitle: "CONTESTED BID",
  dealContext: "Deal context",
  uncontested: "Uncontested",
  contestedOpt: "Contested",
  competingBid: "Competing bid ($)",
  bidEvidence: "Bid evidence",
  evNone: "None",
  evClaimed: "Claimed verbally",
  evVerified: "Verified quote",
  switching: "Switching premium (%)",
  defenseFloor: "Defense floor",
  competitorCeiling: "Competitor ceiling",
  requiredRevenue: "Required revenue",
  willingnessCeiling: "WTP ceiling",
  contestedHint:
    "A verified competing bid caps willingness to pay and relaxes the floor to defense margin over risk-adjusted cost. Unverified claims never move the floor.",
  // Action feedback
  saved: "Saved — governance: %s",
  saveFailed: "Save failed",
  copied: "Markdown copied to clipboard",
  copyFailed: "Copy failed",
  exported: "Markdown downloaded",
  proposalBlocked: "Proposal blocked — only green or approved quotes can generate a customer proposal.",
  proposalFailed: "Proposal generation failed",
  generating: "Working…",
} as const;

export type WsKey = keyof typeof en;

const ja: Record<WsKey, string> = {
  dealWorkspace: "案件ワークスペース",
  owner: "担当",
  updated: "更新",
  offering: "オファリング",
  draft: "下書き — 未保存",
  savedQuote: "見積",
  readOnly: "閲覧専用 — このロールはシミュレーション閲覧のみで、見積は保存できません。",
  step1: "ステップ1 ・ ベースライン",
  step2: "ステップ2 ・ AI提供コスト",
  step3: "ステップ3 ・ 価格モデル",
  population: "対象システムのカスタムオブジェクト数",
  scope: "改修対象オブジェクト",
  hrsPerUnit: "従来工数 / オブジェクト (h)",
  billRate: "ブレンド請求単価 ($/h)",
  costRate: "提供コスト単価 ($/h)",
  coverage: "AIカバレッジ (c)",
  effort: "工数削減率 (e)",
  qa: "人手QA戻し (q)",
  llm: "LLM前提 → t",
  tier: "モデルティア",
  tokIn: "入力Kトークン / obj",
  tokOut: "出力Kトークン / obj",
  overhead: "エージェント再試行オーバーヘッド",
  tokenCostLabel: "AIトークンコスト / オブジェクト (t)",
  platform: "プラットフォーム & ツール (P)",
  discount: "従来価格に対する顧客割引 (d)",
  band: "公開オープニングバンド",
  floorHint: "リスク調整後の最大安全割引 = %s — これを超えるとAIが価値を毀損",
  baseline: "従来ベースライン（AIなし）・ U × h × Rb",
  priceUnit: "価格/obj",
  fourChoices: "同一案件、4つの価格選択",
  fourChoicesSub: "すべてのAIシナリオは同じ提供コスト。価格ロジックのみが異なります。",
  gainShare: "ゲインシェア曲線 — 利益 対 顧客割引",
  gainShareSub: "金色の破線は現在の従来利益（%p）。曲線が交わる d* = %d が最大割引。",
  governance: "案件ガバナンス",
  floor: "単純フロア d*",
  current: "現在 d",
  riskMax: "リスク調整上限",
  gates: "%n ガバナンスゲート",
  gatePass: "適合",
  gateWarn: "警告",
  gateFail: "不可",
  gateSummary: "%p 適合 · %w 警告 · %f 不可",
  showGates: "ゲート詳細を表示",
  hideGates: "ゲート詳細を隠す",
  save: "保存",
  export: "エクスポート",
  generate: "提案書を生成",
  copyMd: "Markdownでコピー",
  rev: "売上",
  cost: "提供コスト",
  gp: "粗利",
  margin: "粗利率",
  revHr: "売上 / 提供時間",
  saves: "顧客の削減額",
  aiEffort: "AI適用後の工数",
  duration: "提供期間",
  perObj: "／オブジェクト",
  vsTradHr: "従来 $%b との比較",
  belowTrad: "従来価格を下回る",
  vsMonths: "従来 %m ヶ月との比較",
  vsTraditional: "従来比",
  selectedPrefix: "選択シナリオ：",
  unitsInScope: "対象 %n %u",
  monthsShort: "ヶ月",
  hoursShort: "時間",
  tokSuffix: "トークン",
  within: "ポリシー適合",
  review: "ディールデスク承認が必要",
  blocked: "ブロック — ポリシーまたは経済フロア未達",
  nobid: "ノービッド／再スコープ",
  msgWithin: "経済性と必須ポリシーゲートを満たしています。営業は公開バンド内で進められます。",
  msgReview: "経済的には成立しますが、公開バンドを超過するか未解決のエビデンス警告があります。ディールデスクへ。",
  msgBlocked:
    "必須ゲートまたはリスク調整後の経済ハードルを満たしていません。この価格で見積もらず、再スコープ・ティア再構成・ノービッドの判断をディールデスクへ。",
  msgNobid:
    "必要なリスク調整後価格が支払意思の上限を超えています。スピード・保証・手戻り総コストで議論するか、スコープを再構成するか、入札を見送ってください — 値引きで合わせないこと。",
  contestedTitle: "競合入札",
  dealContext: "案件コンテキスト",
  uncontested: "競合なし",
  contestedOpt: "競合あり",
  competingBid: "競合入札額 ($)",
  bidEvidence: "入札エビデンス",
  evNone: "なし",
  evClaimed: "口頭での主張",
  evVerified: "検証済み見積",
  switching: "スイッチング・プレミアム (%)",
  defenseFloor: "防衛フロア",
  competitorCeiling: "競合上限",
  requiredRevenue: "必要売上",
  willingnessCeiling: "支払意思上限",
  contestedHint:
    "検証済みの競合入札は支払意思の上限を定め、フロアをリスク調整コスト＋防衛マージンまで緩和します。未検証の主張はフロアを動かしません。",
  saved: "保存しました — ガバナンス: %s",
  saveFailed: "保存に失敗しました",
  copied: "Markdownをクリップボードにコピーしました",
  copyFailed: "コピーに失敗しました",
  exported: "Markdownをダウンロードしました",
  proposalBlocked: "提案書は生成できません — グリーンまたは承認済みの見積のみ生成可能です。",
  proposalFailed: "提案書の生成に失敗しました",
  generating: "処理中…",
};

/** Local-first translate; falls back to the shared i18n dictionary. */
export function tw(key: WsKey, locale: Locale): string {
  return locale === "ja" ? (ja[key] ?? en[key]) : en[key];
}

/** Shared-dictionary passthrough for keys owned by i18n.ts. */
export function tShared(key: string, locale: Locale): string {
  return sharedT(key, locale);
}

/** printf-lite: replaces %s/%p/%d/%n/%u/%b/%m/%w/%f tokens in order given a map. */
export function fill(template: string, vars: Record<string, string>): string {
  let out = template;
  for (const [token, value] of Object.entries(vars)) {
    out = out.split(token).join(value);
  }
  return out;
}
